site_name: EJP Soil - Soil Data Assimilation Guidance
site_description: "Cookbooks for a masterclass on Soil Data Assimilation"
site_author: EJP Soil
copyright: "&copy; 2022 Wageningen Environmental Research"
site_url: https://ejpsoil.github.io/soildata-assimilation-guidance
repo_url: https://github.com/ejpsoil/soildata-assimilation-guidance
docs_dir: docs
nav:
    - Home: index.md

# use_directory_urls: true

#theme:
#    name: null
#    custom_dir: pygeoapi.io-theme

plugins:
    - search