site_name: Soil Data Assimilation Guidance
site_description: "Cookbook for a masterclass on Soil Data Assimilation"
site_author: Wageningen Environmental Research
copyright: "&copy; 2022-2023 Wageningen Environmental Research"
site_url: https://ejpsoil.github.io/soildata-assimilation-guidance
repo_url: https://github.com/ejpsoil/soildata-assimilation-guidance
docs_dir: docs
nav:
    - Identification: identification.md
    - Harmonization: etl.md
    - Code lists: codelists.md
    - Discovery: metadata.md
    - View: view.md
    - Download: download.md
    - QOS: QOS.md

theme:
    name: material
    logo: https://ejpsoil.eu/fileadmin/projects/ejpsoil/EJP_Soil_logo_cmyk-h100.png
    favicon: https://cdn.au.dk/favicon.ico

extra:
  homepage: https://ejpsoil.eu/

plugins:
    - search