site_name: EJP Soil - Soil Data Assimilation Guidance
site_description: "Cookbooks for a masterclass on Soil Data Assimilation"
site_author: EJP Soil
copyright: "&copy; 2022 Wageningen Environmental Research"
site_url: https://ejpsoil.github.io/soildata-assimilation-guidance
repo_url: https://github.com/ejpsoil/soildata-assimilation-guidance
docs_dir: docs
nav:
    - Intro: index.md
    - Identification and namespaces: identification.md
    - Metadata and Discovery: metadata.md
    - Data harmonization (vector): etl.md
    - Code lists: codelists.md
    - View services: view.md
    - Download services: download.md
    - Quality of service: QOS.md

# use_directory_urls: true

#theme:
#    name: null
#    custom_dir: pygeoapi.io-theme

plugins:
    - search