# forked from https://github.com/geonetwork/docker-geonetwork/blob/main/4.2.2/docker-compose.yml
# License GPLv2 GeoNetwork-opensource.org

version: '3.1'

volumes:
  geonetwork:
  pgdata:
  pglog:
  apachelog:
  geoserver-data:


networks:
  gn-network:
    driver: bridge

services:

  database:
    image: postgis/postgis:11-2.5
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - gn-network

  geoserver:
    image: docker.osgeo.org/geoserver:2.21.2
    restart: always
    ports:
      - 8000:8080
    volumes:
        - geoserver-data:/opt/geoserver_data
    environment:
        GEOSERVER_DATA_DIR: /opt/geoserver_data
        GEOSERVER_ADMIN_USER: admin
        GEOSERVER_ADMIN_PASSWORD: geoserver
    networks:
      - gn-network

  geonetwork:
    image: geonetwork:3.12
    restart: always
    ports:
      - 8001:8080
    environment:
      DATA_DIR: /catalogue-data
      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      GEONETWORK_DB_PASSWORD: geonetwork

    volumes:
      - geonetwork:/catalogue-data
    depends_on:
      - database
    networks:
      - gn-network

